steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build and push Docker image
    env:
      DOCKER_IMAGE: 590951457535.dkr.ecr.us-east-1.amazonaws.com/ef-test-k8s
    run: |
      docker build -t $DOCKER_IMAGE .
      docker tag $DOCKER_IMAGE $DOCKER_IMAGE
      docker push $DOCKER_IMAGE

  - name: Deploy Docker container
    env:
      SSH_HOST: "3.92.3.210"
      SSH_PORT: "22"
      SSH_USERNAME: "anil"
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      DOCKER_IMAGE: 590951457535.dkr.ecr.us-east-1.amazonaws.com/ef-test-k8s
    run: |
      sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sudo docker stop docker-test && docker rm docker-test || true"
      sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sudo docker login -u AWS -p \$(aws ecr get-login-password --region us-east-1) 590951457535.dkr.ecr.us-east-1.amazonaws.com"
      sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sudo docker pull $DOCKER_IMAGE"
      sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "sudo docker run -d --name docker-test -p 8080:8080 $DOCKER_IMAGE"
