name: Deploy to EKS dev-exam cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push Docker image to ECR
      id: build-and-push
      env:
        ECR_REGISTRY: 590951457535.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: ef-test-k8s
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        env:
          AWS_REGION: us-east-1
    
    - name: Deploy to EKS
      uses: appleboy/kubectl-action@master
      with:
        args: |
          set image deployment/my-app my-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          -n dev-exam
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
